# Generated by Django 5.0.4 on 2024-04-09 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(choices=[('nit', 'NIT'), ('cc', 'Cédula de ciudadanía')], max_length=3)),
                ('identificacion', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='sistemasusuarios.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('cell', 'Celular'), ('tel', 'Teléfono')], max_length=4)),
                ('numero', models.CharField(max_length=20)),
                ('indicativo', models.CharField(max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='sistemasusuarios.empleado')),
            ],
        ),
    ]
