# Generated by Django 5.0.4 on 2024-04-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemasusuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
